### PR TITLE
Update Constant.py

### PR DESCRIPTION
**Pull request by Martijnde**
I updated the speed of animation in milliseconds from 40 to sth like 80, so when one makes a gif for sharing on social media channels the output after creating a GIF won't be to large for sharing.

### CODE REVIEW

**Comment by Martijnde** [comment]
Update for GIF reduce to enable social channel sharing.

**Comment by Martijnde** [comment]
@rajshah4 look at this great visualization!

**Comment by linouk23** [comment]
Really nice update, thanks!

**Comment by Martijnde** [comment]
Thanks for reaching and helping out, will mention your Github @ socials!

**Comment by Martijnde** [comment]
I deleted the Martijnde:patch-1 branch just now, this because master is up to date

**Pull request merged**
